HealthResearchAuthority/rsp-alz

- .azuredevops/pipelines/application-deployment.yml
- .azuredevops/pipelines/network-deployment.yml
- 5.spoke-network/app-parameters/systemtest_auto.parameters.bicepparam
https://nihr.atlassian.net/browse/RSP-2373
> Deployment stack changes for Auto and Dev environment 

- 5.spoke-network/app-parameters/dev.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_auto.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_manual.parameters.bicepparam
- 5.spoke-network/main.application.bicep
- 5.spoke-network/modules/06-container-app/deploy.container-app.bicep
https://nihr.atlassian.net/browse/RSP-1686
> Add appInsights to container service

- shared/bicep/app-services/function-app.bicep
https://nihr.atlassian.net/browse/RSP-2867
> Enable https traffic on function apps.

- 5.spoke-network/modules/03-supporting-services/modules/app-configuration.bicep
1. Updated App Configuration setting for IDG URL with content type
> idg config correction

- 5.spoke-network/app-parameters/dev.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_auto.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_manual.parameters.bicepparam
- 5.spoke-network/main.application.bicep
- 5.spoke-network/modules/03-supporting-services/deploy.supporting-services.bicep
- 5.spoke-network/modules/03-supporting-services/modules/app-configuration.bicep
- Added required parameters for Gov UK One Loging
- Added feature flags
> RSP-2796: Spike: Integrate with Gov UK Login

- .azuredevops/pipelines/1.core-services.yaml
- .azuredevops/pipelines/3.sub-placement.yaml
- .azuredevops/pipelines/application-deployment.yml
- .azuredevops/pipelines/network-deployment.yml
##[warning]See https://aka.ms/azdo-ubuntu-24.04 for changes to the ubuntu-24.04 image. Some tools (e.g. Mono, NuGet, Terraform) are not available on the image. Therefore some tasks do not run or have reduced functionality.
> Install azure cli as part of the step

- .azuredevops/pipelines/1.core-services.yaml
- .azuredevops/pipelines/3.sub-placement.yaml
- .azuredevops/pipelines/alz-bicep-pr1-build.yml
- .azuredevops/pipelines/alz-bicep-pr2-lint.yml
- .azuredevops/pipelines/application-deployment.yml
- .azuredevops/pipelines/network-deployment.yml
Disable triggers for landing zone repo.
> Remove auto-trigger for landing zone

- 5.spoke-network/main.application.bicep
- 5.spoke-network/modules/03-supporting-services/deploy.supporting-services.bicep
> Remove service bus deployment from supporting services.

- 5.spoke-network/modules/07-app-service/deploy.app-service.bicep
- shared/bicep/storage/storage.bicep
This has been actioned to allow the azure functions deployment (issue raised by Dev team)
> Enable Public access to Storage account

- 5.spoke-network/app-parameters/dev.parameters.bicepparam
- 5.spoke-network/app-parameters/pre_prod.parameters.bicepparam
- 5.spoke-network/app-parameters/production.parameters.bicepparam
- 5.spoke-network/app-parameters/shared.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_auto.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_manual.parameters.bicepparam
- 5.spoke-network/app-parameters/uat.parameters.bicepparam
- 5.spoke-network/main.application.bicep
- 5.spoke-network/modules/05-database/deploy.database.bicep
- Added SQL Server auditing settings with Log Analytics workspace
- Added diagnostics settings for security audit logs 
- Added configurable parameters for retention days and enabling/disabling auditing
> Add SQL Server Auditing with Log Analytics Integration

- 5.spoke-network/app-parameters/dev.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_auto.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_manual.parameters.bicepparam
- 5.spoke-network/main.application.bicep
- 5.spoke-network/modules/03-supporting-services/deploy.supporting-services.bicep
- 5.spoke-network/modules/03-supporting-services/modules/app-configuration.bicep
- Added allowed hosts parameter per environment to support Front Door integration.
- Added feature flag for using Front Door in application configuration.
- Fixed feature flag for MyResearch page.
> RSP-4641: Add support for Front Door in application configuration

- .azuredevops/pipelines/application-deployment.yml
- 5.spoke-network/app-parameters/dev.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_manual.parameters.bicepparam
- 5.spoke-network/main.application.bicep
- 5.spoke-network/modules/03-supporting-services/deploy.supporting-services.bicep
- 5.spoke-network/modules/03-supporting-services/modules/app-configuration.bicep
Implement Microsoft Clarity
[RSP-4089](https://nihr.atlassian.net/browse/RSP-4089)
Put [X] inside the [] to make the box ticked
- [] Refactoring
- [] Bug-fix
- [] DevOps
- [] Testing
> RSP-4089: Microsoft Clarity PoC

- .azuredevops/pipelines/application-deployment.yml
This reverts commit 618f005b780e5f60166e976d3a280a45d3394cf2.
> Revert "Add OneLoginPrivateKeyPem pipeline parameter (#50)"

- .azuredevops/pipelines/6.cross-subscription.yaml
- 5.spoke-network/app-parameters/systemtest_auto.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_manual.parameters.bicepparam
- 5.spoke-network/main.application.bicep
- 5.spoke-network/modules/03-supporting-services/deploy.supporting-services.bicep
- 5.spoke-network/modules/07-app-service/deploy.app-service.bicep
1. Key Vault integration in to Cross Subscription Pipeline
2. Update IP Config format
3. re-order deployments to avoid Private DNS deployment conflicts
> Pipeline Key vault integration

- .azuredevops/pipelines/1.core-services.yaml
- .azuredevops/pipelines/3.sub-placement.yaml
- .azuredevops/pipelines/6.cross-subscription.yaml
- .azuredevops/pipelines/application-deployment.yml
- .azuredevops/pipelines/dw-application-deployment.yml
- .azuredevops/pipelines/dw-network-deployment.yml
- .azuredevops/pipelines/network-deployment.yml
- 5.spoke-network/app-parameters/dev.parameters.bicepparam
- 5.spoke-network/network-parameters/dev.parameters.bicepparam
Adds a SAST scanning job to the deployment pipeline to check for security vulnerabilities in Bicep code.
JIRA ticket : https://nihr.atlassian.net/browse/RSP-3587
> Add SAST scanning to CI/CD deployment pipeline

- .azuredevops/pipelines/6.cross-subscription.yaml
- .azuredevops/pipelines/application-deployment.yml
- 5.spoke-network/app-parameters/systemtest_auto.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_manual.parameters.bicepparam
- 5.spoke-network/modules/03-supporting-services/modules/app-configuration.bicep
- 6.cross-subscription/main.bicep
- shared/bicep/app-services/web-app.bicep
1. Key Vault Integration with Pipeline variables
2. GOV Login Auth Session updated to 60min
3. Enabling Frontdoor
> Keyvaultintegration

- .azuredevops/pipelines/application-deployment.yml
- 5.spoke-network/app-parameters/dev.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_auto.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_manual.parameters.bicepparam
- 5.spoke-network/main.application.bicep
- 5.spoke-network/modules/03-supporting-services/deploy.supporting-services.bicep
- 5.spoke-network/modules/03-supporting-services/modules/app-configuration.bicep
[RSP-4916](https://nihr.atlassian.net/browse/RSP-4916)
> RSP-4916: Logout from auth provider

- .azuredevops/pipelines/application-deployment.yml
- 5.spoke-network/app-parameters/dev.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_auto.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_manual.parameters.bicepparam
- 5.spoke-network/main.application.bicep
- 5.spoke-network/modules/03-supporting-services/deploy.supporting-services.bicep
- 5.spoke-network/modules/03-supporting-services/modules/app-configuration.bicep
Google Analytics integration
[RSP-4914](https://nihr.atlassian.net/browse/RSP-4914)
Put [X] inside the [] to make the box ticked
- [] Refactoring
- [] Bug-fix
- [] DevOps
- [] Testing
> RSP-4914: Google Analytics integration

- 5.spoke-network/app-parameters/dev.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_auto.parameters.bicepparam
- 5.spoke-network/app-parameters/systemtest_manual.parameters.bicepparam
- 5.spoke-network/app-parameters/uat.parameters.bicepparam
- 5.spoke-network/main.application.bicep
- 5.spoke-network/modules/03-supporting-services/modules/app-configuration.bicep
- README.md
https://nihr.atlassian.net/browse/RSP-5092
> Remove questionset service

- 5.spoke-network/modules/03-supporting-services/modules/app-configuration.bicep
Rename PortalUrl to AppSettings:PortalUrl
> Rename PortalUrl to AppSettings:PortalUrl
